//! Render a DRAFT flight plan from a server's `tools/list`.
//!
//! gurgl NEVER runs this draft and NEVER fuzzes arguments: it writes inert
//! `REPLACE_ME` placeholders to disk for a human to review and fill in. Only
//! tools whose NAME looks read-only (a lexical heuristic, `observe::tool_looks_unsafe`)
//! get a step - never a judgement about what a tool actually does. A generated or
//! edited plan is a new METHOD: its fingerprint differs from `default`, so
//! snapshots captured under it are not comparable to default-plan snapshots. The
//! rendered header says all of this. Pure - `toml::to_string` drops comments, so
//! the TOML is hand-emitted and guarded by a round-trip test.

use serde_json::Value;

use crate::observe::{tool_looks_unsafe, ToolDef};

/// Cap on scaffolded tool-call steps, so a server advertising a huge tool list
/// cannot produce an enormous file. If exceeded, the overflow is disclosed in a
/// comment (never silently dropped).
const MAX_STEPS: usize = 60;

/// Render a draft flight plan (valid, commented TOML) for `server` from `tools`.
pub fn render_draft_plan(server: &str, tools: &[ToolDef]) -> String {
    let mut s = String::new();
    s.push_str("# DRAFT flight plan generated by `gurgl plan` - REVIEW before use.\n");
    s.push_str("#\n");
    s.push_str("# gurgl did NOT run this and did NOT fill in real arguments. Each tools/call\n");
    s.push_str("# step below is a candidate carrying REPLACE_ME placeholders; edit them to real\n");
    s.push_str("# values or delete the step. Only tools whose NAME looks read-only were\n");
    s.push_str("# scaffolded (a lexical heuristic, not a judgement about what the tool does) -\n");
    s.push_str("# read every step before you run it.\n");
    s.push_str("#\n");
    s.push_str("# This plan is a NEW method: its fingerprint differs from `default`, so\n");
    s.push_str("# snapshots captured under it are NOT comparable to default-plan snapshots, and\n");
    s.push_str("# editing it changes the fingerprint again. Wire it up in gurgl.toml with:\n");
    s.push_str(&format!(
        "#   flightplan = \"flightplans/{}.toml\"\n",
        one_line(server)
    ));
    s.push('\n');

    // The plan name feeds the fingerprint; keep it tied to the server so distinct
    // servers' drafts fingerprint differently.
    s.push_str(&format!("name = {}\n\n", toml_string(server)));

    // Fixed scaffolding, mirroring flightplans/default.toml.
    s.push_str("[[steps]]\nphase = \"startup\"\naction = \"initialize\"\n\n");
    s.push_str("[[steps]]\nphase = \"enumerate\"\naction = \"tools/list\"\n\n");

    let mut emitted = 0usize;
    for t in tools {
        if t.name.is_empty() || tool_looks_unsafe(&t.name) {
            continue;
        }
        if emitted >= MAX_STEPS {
            s.push_str(&format!(
                "# ... additional read-only-looking tools were omitted (cap {MAX_STEPS}); add them\n\
                 # by hand if you want them exercised.\n\n"
            ));
            break;
        }
        if let Some(desc) = &t.description {
            let d = one_line(desc);
            if !d.is_empty() {
                s.push_str(&format!("# {}: {}\n", one_line(&t.name), d));
            }
        }
        s.push_str("[[steps]]\n");
        s.push_str("phase = \"tool-call\"\n");
        s.push_str("action = \"tools/call\"\n");
        s.push_str(&format!("tool = {}\n", toml_string(&t.name)));
        s.push_str(&format!(
            "args = {}   # fill in real values, or delete this step\n\n",
            placeholder_args_for_schema(&t.input_schema)
        ));
        emitted += 1;
    }
    if emitted == 0 {
        s.push_str(
            "# No read-only-looking tools were found to scaffold. Add tools/call steps by\n",
        );
        s.push_str("# hand (see flightplans/default.toml), keeping them read-only.\n\n");
    }

    s.push_str("[[steps]]\nphase = \"idle\"\naction = \"sleep\"\nseconds = 8\n");
    s
}

/// A TOML inline table of REPLACE_ME placeholders for a tool's required inputs,
/// typed from its JSON-Schema `inputSchema`. Handles the common
/// `{type:object, properties, required}` shape; anything unrecognized becomes an
/// empty object placeholder for the user to fill by hand. Never claims completeness.
fn placeholder_args_for_schema(schema: &Value) -> String {
    let Some(props) = schema.get("properties").and_then(|p| p.as_object()) else {
        return "{}".to_string();
    };
    let required: Vec<&str> = schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();

    let mut parts: Vec<String> = Vec::new();
    for key in &required {
        let Some(pschema) = props.get(*key) else {
            continue;
        };
        let placeholder = match pschema.get("type").and_then(|t| t.as_str()) {
            Some("string") => "\"REPLACE_ME\"".to_string(),
            Some("integer") | Some("number") => "0".to_string(),
            Some("boolean") => "false".to_string(),
            Some("array") => "[]".to_string(),
            // object / unknown / union types: an object placeholder to fill by hand.
            _ => "{}".to_string(),
        };
        parts.push(format!("{} = {}", toml_key(key), placeholder));
    }
    if parts.is_empty() {
        return "{}".to_string();
    }
    format!("{{ {} }}", parts.join(", "))
}

/// A TOML bare key if it is one, else a quoted key. Keeps the emitted table valid
/// for attacker-influenced schema property names.
fn toml_key(k: &str) -> String {
    if !k.is_empty()
        && k.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        k.to_string()
    } else {
        toml_string(k)
    }
}

/// A valid TOML basic string with escaping - the values here are server-supplied.
fn toml_string(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Collapse a possibly-multiline, control-laden server string to one trimmed
/// line, truncated - so it is safe to emit as a single TOML comment.
fn one_line(s: &str) -> String {
    let cleaned: String = s
        .chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect();
    let joined = cleaned.split_whitespace().collect::<Vec<_>>().join(" ");
    if joined.chars().count() > 100 {
        let head: String = joined.chars().take(97).collect();
        format!("{head}...")
    } else {
        joined
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::flightplan::FlightPlan;
    use serde_json::json;

    fn tool(name: &str, schema: Value) -> ToolDef {
        ToolDef {
            name: name.to_string(),
            description: Some(format!("does {name}")),
            input_schema: schema,
        }
    }

    fn render(tools: &[ToolDef]) -> String {
        render_draft_plan("my-server", tools)
    }

    #[test]
    fn draft_round_trips_through_flightplan_load() {
        let tools = vec![
            tool(
                "search",
                json!({"type":"object","properties":{"q":{"type":"string"}},"required":["q"]}),
            ),
            tool("list_items", json!({"type":"object"})),
            tool("delete_thing", json!({"type":"object"})), // unsafe: excluded
        ];
        let text = render(&tools);
        // Hand-emitted TOML must parse as a real flight plan.
        let dir = std::env::temp_dir().join(format!("gurgl-plan-{}.toml", std::process::id()));
        std::fs::write(&dir, &text).unwrap();
        let plan = FlightPlan::load(&dir).unwrap();
        let _ = std::fs::remove_file(&dir);
        // Scaffolding present.
        assert!(plan.steps.iter().any(|s| s.action == "initialize"));
        assert!(plan.steps.iter().any(|s| s.action == "tools/list"));
        assert!(plan.steps.iter().any(|s| s.action == "sleep"));
        // A step for each read-only-looking tool, none for the unsafe one.
        let called: Vec<&str> = plan
            .steps
            .iter()
            .filter(|s| s.action == "tools/call")
            .filter_map(|s| s.tool.as_deref())
            .collect();
        assert!(called.contains(&"search"));
        assert!(called.contains(&"list_items"));
        assert!(!called.contains(&"delete_thing"));
    }

    #[test]
    fn placeholder_types_map_correctly() {
        let schema = json!({
            "type":"object",
            "properties":{
                "url":{"type":"string"},
                "count":{"type":"integer"},
                "flag":{"type":"boolean"},
                "tags":{"type":"array"},
                "opt":{"type":"string"}
            },
            "required":["url","count","flag","tags"]
        });
        let args = placeholder_args_for_schema(&schema);
        assert!(args.contains("url = \"REPLACE_ME\""));
        assert!(args.contains("count = 0"));
        assert!(args.contains("flag = false"));
        assert!(args.contains("tags = []"));
        // A non-required prop is omitted.
        assert!(!args.contains("opt"));
        // No properties -> empty inline table.
        assert_eq!(placeholder_args_for_schema(&json!({"type":"object"})), "{}");
    }

    #[test]
    fn header_never_calls_anything_safe_or_verified() {
        // Constraint #1: the draft must not imply a safety verdict.
        let text = render(&[tool("get_it", json!({"type":"object"}))]).to_lowercase();
        for forbidden in ["safe", "clean", "verified"] {
            assert!(
                !text.contains(forbidden),
                "draft must not contain '{forbidden}'"
            );
        }
        // It DOES warn about the fingerprint / reproduction-gate implication.
        assert!(text.contains("fingerprint"));
    }

    #[test]
    fn no_tools_still_yields_a_valid_scaffold() {
        let text = render(&[]);
        let dir =
            std::env::temp_dir().join(format!("gurgl-plan-empty-{}.toml", std::process::id()));
        std::fs::write(&dir, &text).unwrap();
        let plan = FlightPlan::load(&dir).unwrap();
        let _ = std::fs::remove_file(&dir);
        assert!(plan.steps.iter().any(|s| s.action == "initialize"));
        assert!(!plan.steps.iter().any(|s| s.action == "tools/call"));
    }

    #[test]
    fn attacker_influenced_names_stay_valid_toml() {
        // A tool name with a quote / control char must not break the TOML.
        let text = render(&[tool("we\"ird\tname-get", json!({"type":"object"}))]);
        let dir = std::env::temp_dir().join(format!("gurgl-plan-evil-{}.toml", std::process::id()));
        std::fs::write(&dir, &text).unwrap();
        let plan = FlightPlan::load(&dir);
        let _ = std::fs::remove_file(&dir);
        assert!(plan.is_ok(), "hand-emitted TOML must stay valid: {plan:?}");
    }
}
